# ---------------
# _config.yml
#         1：编译相关配置
#         2：URL显示
#         3：默认值设置
#         4：全局常量  （通过site可以获取）
#             4.1：预设
#             4.2：用户自定义
#
#  注意： _config.yml的修改不会自动更新--可以在_data(Jekyll's data files)中添加
#         -- 使用命令# 'bundle exec jekyll serve' 调试时文件修改会自动更新（及时的成成site）
#
# ---------------

#-------------------
#   1：Build settings
#-------------------
highlighter: rouge
markdown: kramdown
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
kramdown:
  input:  GFM
  syntax_highlighter: rouge
  coderay_default_lang: objc
  extensions:
    - autolink
    - footnotes
    - smart


# markdown: kramdown
highlighter: pygments # 使用pygments来处理语法高亮
# auto: true  # 自动处理更新
LSI : true  # 开启相关文章推荐
# theme: minima

# exclude:
#   - "README.md"
#   - "CHANGELOG.md"
#   - "CNAME"
#   - "Gemfile"
#   - "Gemfile.lock"

#翻页效果
paginate: 10
paginate_baseurl: "/homePaginate/"
paginate_path: "/homePaginate/page:num"


#-------------------
#   2：URL 相关设置
#-------------------
baseurl: ""     # the subpath of your site, e.g. /blog
url: ""   # the base hostname & protocol for your
#url样式
permalink: /:categories/:year/:month/:day/:title



#-------------------
#   3：默认值设置
#-------------------
# defaults:
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "default"
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"



# ---------------
#   4：Site settings 全局常量
# ---------------

#   通过  {{ site.title }} 方式获取变量
#   常量-- 原因是对_config的修改不会自动更新 必须手动编译 jekyll serve
#   时常修改的变量--或者希望修改后自动更新（watch）使用_data file

#不同的方式来定义属性 -- 扁平化
title: HLNotes
email: config_email
description: config_description
site_copyright:     © All Rights Reserved.

#TODO
# twitter_username: jekyllrb
# github_username:  jekyll
# google_analytics:   UA-44768500-1

repository: hailongiphone.github.io
#不同的方式来定义属性 -- 类聚

author :
  name : HalLong
  email : guohailong.hh@gmail.com
  github : hailongiphone
  twitter : HaiLongGuo

var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html



gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-compose
